name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - terraform/*

resources:
  repositories:
    - repository: infra-repo
      type: github
      name: your-org/infra-repo
      ref: refs/heads/staging
      endpoint: githubServiceConnection

variables:
  - group: terraform-vars
  - name: TF_VERSION
    value: 1.8.2
  - name: ENVIRONMENT
    value: STAGING

stages:
- stage: Plan
  jobs:
  - job: Generate_TFPlan
    steps:
    - task: TerraformCLI@0
      inputs:
        command: init
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc'

    - task: TerraformCLI@0
      inputs:
        command: plan
        commandOptions: '-var-file=../config/$(ENVIRONMENT).tfvars -out=tfplan'
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc'

    - publish: $(System.DefaultWorkingDirectory)/terraform/tfplan
      artifact: tfplan

- stage: Apply
  dependsOn: Approve
  jobs:
  - job: Execute_TFApply
    steps:
    - download: current
      artifact: tfplan
    - task: TerraformCLI@0
      inputs:
        command: apply
        commandOptions: 'tfplan' # vars embedded in tfplan
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc'
