name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/*
      - config/*
      - modules/*

pr: none # Do not run on PR

pool:
  name: Azure Pipelines

resources:
  repositories:
    - repository: infra-repo
      type: github
      name: OL-Smart-Clicker/infra-repo
      ref: refs/heads/main
      endpoint: 'Smart Clicker 2.0'

variables:
  - name: ENVIRONMENT
    value: PRODUCTION
  - name: BACKEND_CONFIG_FILE
    value: ../config/backend-production.hcl

stages:
- stage: Plan
  jobs:
  - job: Generate_TFPlan
    steps:
    # Install Terraform 1.11.2
    - task: TerraformInstaller@1
      displayName: 'Install Terraform 1.11.2'
      inputs:
        terraformVersion: 1.11.2

    # Initialize Terraform for Production
    - task: TerraformCLI@1
      inputs:
        command: init
        commandOptions: '-backend-config=$(BACKEND_CONFIG_FILE) -input=false'
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-production'

    # Generate Terraform plan
    - task: TerraformCLI@1
      inputs:
        command: plan
        commandOptions: '-var-file=../config/$(ENVIRONMENT).tfvars -out=tfplan'
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-production'

    # Publish the tfplan artifact for later use in Apply
    - publish: $(System.DefaultWorkingDirectory)/terraform/tfplan
      artifact: tfplan-artif-prod

- stage: Approve
  dependsOn: Plan
  jobs:
  - job: Manual_Approval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please review the Terraform plan and approve if the changes are acceptable.'
        onTimeout: 'reject'

- stage: Apply
  dependsOn: Approve
  jobs:
  - job: Execute_TFApply
    steps:
    - download: current
      artifact: tfplan-artif-prod
    - task: TerraformInstaller@1
      displayName: 'Install Terraform 1.11.2'
      inputs:
        terraformVersion: 1.11.2
    - task: TerraformCLI@1
      inputs:
        command: init
        commandOptions: '-backend-config=$(BACKEND_CONFIG_FILE) -input=false'
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-production'
    - task: TerraformCLI@1
      inputs:
        command: apply
        commandOptions: '$(Pipeline.Workspace)/tfplan-artif-prod/tfplan'  # vars embedded in tfplan
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-production'