name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - staging
  paths:
    include:
      - terraform/*
      - config/*

pr: none # Do not run on PR

# TEMPORARY
pool:
  name: Self-hosted

resources:
  repositories:
    - repository: infra-repo
      type: github
      name: OL-Smart-Clicker/infra-repo
      ref: refs/heads/staging
      endpoint: 'Smart Clicker 2.0'

variables:
  - name: ENVIRONMENT
    value: STAGING

stages:
- stage: Plan
  jobs:
  - job: Generate_TFPlan
    steps:
    # Install Terraform 1.11.2
    - task: TerraformInstaller@1
      displayName: 'Install Terraform 1.11.2'
      inputs:
        terraformVersion: 1.11.2

    # Initialize Terraform for Staging
    - task: TerraformCLI@1
      inputs:
        command: init
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-staging'

    # Generate Terraform plan
    - task: TerraformCLI@1
      inputs:
        command: plan
        commandOptions: '-var-file=../config/$(ENVIRONMENT).tfvars -out=tfplan'
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-staging'

    # Publish the tfplan artifact for later use in Apply
    - publish: $(System.DefaultWorkingDirectory)/terraform/tfplan
      artifact: tfplan

- stage: Approve
  dependsOn: Plan
  jobs:
  - deployment: Manual_Approval
    environment: Staging 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualIntervention@8
            inputs:
              instructions: 'Please review the changes and approve the deployment to Staging.'
              onTimeout: 'reject'

- stage: Apply
  dependsOn: Approve
  jobs:
  - job: Execute_TFApply
    steps:
    - download: current
      artifact: tfplan
      path: $(System.DefaultWorkingDirectory)/terraform
    - task: TerraformCLI@1
      inputs:
        command: apply
        commandOptions: '$(System.DefaultWorkingDirectory)/terraform/tfplan'  # vars embedded in tfplan
        workingDirectory: 'terraform'
        environmentServiceName: 'tf-pipeline-sc-staging'