controller:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
  extraArgs:
    default-ssl-certificate: frontend/tls-secret