apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-cert-sync
  namespace: frontend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.irsa_id }}
    keyvaultName: {{ .Values.keyvault_name }}
    tenantId: {{ .Values.tenant_id }}
    objects: |
      array:
        - |
          objectName: frontend-tls-cert-chain
          objectType: secret
        - |
          objectName: frontend-tls-key
          objectType: secret
  secretObjects:
  - secretName: tls-secret
    type: kubernetes.io/tls
    data:
      - objectName: frontend-tls-cert-chain
        key: tls.crt
      - objectName: frontend-tls-key
        key: tls.key

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-sync
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sync
  template:
    metadata:
      labels:
        app: secret-sync
    spec:
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      containers:
        - name: secret-sync
          image: busybox
          command: ["sleep", "7200"]
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "frontend-cert-sync"